# NB: NumPy First Steps



## NumPy

<img src="../../media/numpy-logo.png" style="float:right;"/>


**A new data structure**

Essentially, NumPy introduces a new data structure to Python &mdash; the **n-dimensional array**. 

Along with it, it introduces a collection of **functions and methods** that take advantage of this data structure.

The data structure is designed to support the use of **numerical methods**: algorithmic approximations to the problems of mathematical analysis.

**New Functions**

It also provides a new way of applying functions to data made possible by the data structure -- **vectorized functions**. 

Vectorized functions **replace the use of loops** and comprehensions to apply a function to a set of data. 

In addition, given the data structure, it provides a library of **linear algebra** functions. 

**New Data Types**

NumPy also introduces a bunch of new **data types**.

**Python for Science**

NumPy stands for "**Numerical Python**".

Because [numerical methods](https://www.britannica.com/science/numerical-analysis) are so important to so many sciences, NumPy is the basis of what is called **the scientific "stack"** in Python, which consists of SciPy, Matplotlib, SciKitLearn, and Pandas. 



All of these assume that you have some knowledge of NumPy.

Let's take a look at it.

## Importing the Library

In [1]:
import numpy as np

NumPy is by widespread convention aliased as `np`.

## The ndarray

The ndarray is a multidimensional array object.

Let's explore it some. 

First, let's generate some fake data using NumPy's built-a random number generator.

Note that `np.random.randn()` samples from the "standard normal" distribution.

In [2]:
# np.random.randn?

In [3]:
data = np.random.randn(2, 3)

In [4]:
data

array([[ 0.51609076,  0.02200193,  0.28980768],
       [ 0.52792978, -0.13494062,  1.8213642 ]])

In [5]:
data * 10

array([[ 5.16090755,  0.22001927,  2.89807681],
       [ 5.27929783, -1.34940618, 18.21364201]])

In [6]:
data + data

array([[ 1.03218151,  0.04400385,  0.57961536],
       [ 1.05585957, -0.26988124,  3.6427284 ]])

In [7]:
data.shape

(2, 3)

In [8]:
data.dtype

dtype('float64')

## About Dimensions

The term "dimension" is ambiguous.

* Sometimes refers to the dimensions of things in the world, such as space and time.
* Sometimes refers to the dimensions of a data structure, independent of what it represents in the world.

NumPy dimensions are the latter, although they can be used to represent the former, as physicists do.

The dimensions of data structures are sometimes called **axes**.

Consider this: Three-dimensional space can be represented as three columns in a two-dimensional table OR as three axes in a data cube. 

## Creating ndarrays

From a list:

In [9]:
data1 = [6, 7.5, 8, 0, 1]
arr1 = np.array(data1)
arr1

array([6. , 7.5, 8. , 0. , 1. ])

From a list of lists:

In [10]:
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]
arr2 = np.array(data2)
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [11]:
arr2.ndim

2

In [12]:
arr2.shape

(2, 4)

In [13]:
arr1.dtype

dtype('float64')

In [14]:
arr2.dtype

dtype('int64')

Initializing with $0$s using a convenience function:

In [15]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [16]:
np.zeros((3, 6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [17]:
np.empty((2, 3, 2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

Using `.arange()` (instead of `range()`)

In [18]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

## Data Types for ndarrays

Unlike any of the previous data structures we have seen in Python, 
**ndarrays must have a single data type** associated with them.

Here we initialize a series of arrays as different data types (aka `dtypes`).

In [19]:
arr1 = np.array([1, 2, 3], dtype=np.float64)
arr1.dtype

dtype('float64')

Note that dtypes are defined by some **constants attached to the NumPy object**.

We can also refer to them as strings in some contexts. 

In other words, in the context of the dtype argument, `'float64'` can substitute for `np.float64`.

In [20]:
np.array([1, 2, 3], dtype='float64')

array([1., 2., 3.])

In [21]:
arr2 = np.array([1, 2, 3], dtype=np.int32)
arr2.dtype

dtype('int32')

Integer arrays default to `int64`:

In [22]:
arr = np.array([1, 2, 3, 4, 5])
arr.dtype

dtype('int64')

So you may want in use a more capacious type:

In [23]:
float_arr = arr.astype(np.float64)
float_arr.dtype

dtype('float64')

Arrays can be cast:

In [24]:
arr = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1])
arr

array([ 3.7, -1.2, -2.6,  0.5, 12.9, 10.1])

From floats to ints:

In [25]:
arr.astype(np.int32)

array([ 3, -1, -2,  0, 12, 10], dtype=int32)

From strings to floats:

In [26]:
numeric_strings = np.array(['1.25', '-9.6', '42'], dtype=np.string_)
numeric_strings.astype(float)

array([ 1.25, -9.6 , 42.  ])

Note that NumPy converts data types to make the array uniform:

In [27]:
non_uniform = np.array([1.25, -9.6, 42])
non_uniform, non_uniform.dtype

(array([ 1.25, -9.6 , 42.  ]), dtype('float64'))

Ranges default to integers:

In [28]:
int_array = np.arange(10)

In [29]:
int_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

We can use the dtype on one array to cast another:

In [30]:
calibers = np.array([.22, .270, .357, .380, .44, .50], dtype=np.float64)
int_array.astype(calibers.dtype)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

And here is an empty array of unsigned integers:

In [31]:
empty_uint32 = np.empty(8, dtype='u4')
empty_uint32

array([         0, 1075314688,          0, 1075707904,          0,
       1075838976,          0, 1072693248], dtype=uint32)

**NumPy Data Types**

```
i - integer
b - boolean
u - unsigned integer
f - float
c - complex float
m - timedelta
M - datetime
O - object
S - string
U - unicode string
V - fixed chunk of memory for other type ( void )
```

**Data Type Hierarchy**

NumPy introduces 24 new fundamental Python types to describe different types of scalars.

These derive from the C programming language with which NumPy is built.

![](../../media/dtype-hierarchy.png)

See the [NumPy docs](https://numpy.org/doc/1.25/reference/arrays.scalars.html).

## Element-wise Arithmetic

NumPy arrays can be transformed with with arithmetic operations.

These are all **element-wise operations**.

Let's start with a 2D array.

In [32]:
arr = np.array([[1., 2., 3.], [4., 5., 6.]])
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [33]:
arr.shape

(2, 3)

In [34]:
arr * arr

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [35]:
arr - arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [36]:
1 / arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [37]:
arr ** 0.5

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

Now let's compare two arrays.

In [38]:
arr2 = np.array([[0., 4., 1.], [7., 2., 12.]])
arr2

array([[ 0.,  4.,  1.],
       [ 7.,  2., 12.]])

In [39]:
arr2 > arr

array([[False,  True, False],
       [ True, False,  True]])

Boolean arrays will prove to be very useful ...

## Indexing and Slicing

**Example 1**

&rarr; _Editor's Note, this jumps ahead to multi-dimensional indexing._

In [40]:
foo = np.random.randn(3,5)

In [41]:
foo

array([[ 0.62543484, -0.96229943,  0.95196573, -0.51305197, -0.1115699 ],
       [ 0.11019503, -0.10980058,  0.28150877, -0.51208741, -0.75206119],
       [ 1.69514313, -1.08493512,  0.1422037 , -0.8920906 , -0.71471137]])

In [42]:
foo.shape

(3, 5)

In [43]:
foo[1:, :2]

array([[ 0.11019503, -0.10980058],
       [ 1.69514313, -1.08493512]])

In [44]:
foo[1:, :2].shape

(2, 2)

Why is this different?

In [45]:
foo[1:][:2]

array([[ 0.11019503, -0.10980058,  0.28150877, -0.51208741, -0.75206119],
       [ 1.69514313, -1.08493512,  0.1422037 , -0.8920906 , -0.71471137]])

Because it operations in sequence, not simultaneously.

In [46]:
a = foo[1:]
a

array([[ 0.11019503, -0.10980058,  0.28150877, -0.51208741, -0.75206119],
       [ 1.69514313, -1.08493512,  0.1422037 , -0.8920906 , -0.71471137]])

In [47]:
a[:2]

array([[ 0.11019503, -0.10980058,  0.28150877, -0.51208741, -0.75206119],
       [ 1.69514313, -1.08493512,  0.1422037 , -0.8920906 , -0.71471137]])

**Example 2**

In [48]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [49]:
arr[5]

5

In [50]:
arr[5:8]

array([5, 6, 7])

Slices can be used to set values as well.

In [51]:
arr[5:8] = 12

In [52]:
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

## Views and Copies

Notice that if we assign a scalar to a slice, all of the elements of the slice get that value. 

This is called **broadcasting**. We'll look at this more later.

Also, notice that changes to slices are changes to the arrays they are slices of. 

They are **views**, not copies. **This is crucial.**

See what happens when we change a view:

In [53]:
arr_slice = arr[5:8]
arr_slice

array([12, 12, 12])

In [54]:
arr_slice[1] = 12345
arr

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,
           9])

In [55]:
arr_slice[:] = 64

In [56]:
arr_slice

array([64, 64, 64])

In [57]:
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

NumPy defaults to views rather than copies because copies are **expensive** and NumPy is designed with large data use cases in mind.

If you want a copy of a slice of an ndarray instead of a view, use `.copy()`.

Here's an example:

In [58]:
arr_slice_copy = arr[5:8].copy()

In [59]:
arr_slice_copy

array([64, 64, 64])

In [60]:
arr_slice_copy[:] = 99

In [61]:
arr_slice_copy

array([99, 99, 99])

Note how the original array is unchanged:

In [62]:
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

## Higher Dimensional Arrays

 NumPy can create arrays in N dimensions.
 
 Here is a 2D array initialized from a list of lists.

In [63]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

Indexing into a dimension produces lower-order arrays.

In [64]:
arr2d[2]

array([7, 8, 9])

In [65]:
arr2d[0][2]

3

**Simplified notation:** NumPy offers an elegant way to specify multidimensional indices and slices.

Instead of `x[a][b][c]` you can write `x[a,b,c]`.

In [66]:
arr2d[0, 2]

3

A nice visual of a 2D array

<img src="https://learning.oreilly.com/api/v2/epubs/urn:orm:book:9781449323592/files/httpatomoreillycomsourceoreillyimages2172112.png" height="50%" width="50%"/>

**Two-Demensional Array Slicing**

<img src="https://learning.oreilly.com/api/v2/epubs/urn:orm:book:9781449323592/files/httpatomoreillycomsourceoreillyimages2172114.png" height="50%" width="50%"/>

**3D arrays**

In [67]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

In [68]:
arr3d.shape

(2, 2, 3)

In [69]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

I find NumPy's way of show the data a bit difficult to parse visually.

**Here is a way to visualize 3 and higher dimensional data:**

```python
[ # AXIS 0                     AXIS 1 CONTAINS 2 ELEMENTS (arrays)
    [ # AXIS 1                 EACH MEMBER OF AXIS 2 CONTAINS 2 ELEMENTS (arrays)
        [1, 2, 3], # AXIS 2    EACH MEMBER OF AXIS 3 CONTAINS 3 ELEMENTS (integers)
        [4, 5, 6]  # AXIS 2
    ],  
    [ # AXIS 1
        [7, 8, 9], 
        [10, 11, 12]
    ]
]
```
Each axis is a level in the nested hierarchy, i.e. a tree or DAG (directed-acyclic graph).

* Each axis is a container.
* There is only one top container.
* Only the bottom containers have data.

**Omit lower indices**

In multidimensional arrays, if you omit later indices, the returned object will be a **lower-dimensional ndarray** consisting of all the data contained by the higher indexed dimension. 

So in the 2 × 2 × 3 array `arr3d`:

In [70]:
arr3d[0] # The elements contained by the first row

array([[1, 2, 3],
       [4, 5, 6]])

Saving data before modifying an array.

You can work with these lower dimensional arrays using views and copies.

In [71]:
old_values = arr3d[0].copy() # Make a copy
arr3d[0] = 42                # Use a view to alter the original
arr3d                        # See result

array([[[42, 42, 42],
        [42, 42, 42]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

Putting the data back.

In [72]:
arr3d[0] = old_values
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

Similarly, `arr3d[1, 0]` gives you all of the values whose indices start with (1, 0), forming a 1-dimensional array:

In [73]:
arr3d[1, 0]

array([7, 8, 9])

In [74]:
x = arr3d[1]
x

array([[ 7,  8,  9],
       [10, 11, 12]])

In [75]:
x[0]

array([7, 8, 9])

## Indexing 2D arrays with slices

We demonstrate indexing in 2D arrays.

In [76]:
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [77]:
arr[1:6]

array([ 1,  2,  3,  4, 64])

In [78]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [79]:
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [80]:
arr2d[:2, 1:]

array([[2, 3],
       [5, 6]])

In [81]:
arr2d[1, :2]

array([4, 5])

In [82]:
arr2d[:2, 2]

array([3, 6])

In [83]:
arr2d[:, :1]

array([[1],
       [4],
       [7]])

In [84]:
arr2d[:2, 1:] = 0
arr2d

array([[1, 0, 0],
       [4, 0, 0],
       [7, 8, 9]])

## Boolean Indexing

This a crucial topic -- it applies to Pandas and R. 

You can pass a boolean representation of an array to the array indexer (i.e. the `[]` suffix) 
and it will return only those cells that are `True`.

Let's assume that we have two related arrays:
* `names` which holds the names associated with the data in each row, or **observations**, of a table.
* `data` which holds the data associated with each **feature** of a table.

There are $7$ observations and $4$ features.

In [85]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [86]:
data = np.random.randn(7, 4)
data

array([[-0.02296517,  0.13474624, -1.68950219,  0.38049711],
       [ 0.26840002,  1.04588115, -0.27682064,  1.34172096],
       [ 0.5600871 ,  0.40689673, -1.01778694, -1.26397703],
       [-0.30857368,  0.13819812, -0.51737801, -0.25058465],
       [-0.41433972, -0.31894006,  0.13259035, -0.78374819],
       [ 0.25037425, -0.09460502, -0.08853394, -1.96423597],
       [ 1.20040478, -0.03586405, -0.85179925,  0.02612226]])

In [87]:
names.shape, data.shape

((7,), (7, 4))

A comparison operation for an array returns an array of booleans.

Let's see which names are `'Bob'`:

In [88]:
names == 'Bob'

array([ True, False, False,  True, False, False, False])

Now, this boolean expression can be passed to an array indexer to the data:

In [89]:
data[names == 'Bob']

array([[-0.02296517,  0.13474624, -1.68950219,  0.38049711],
       [-0.30857368,  0.13819812, -0.51737801, -0.25058465]])

Along the second axis, we can use a slice to select data.

In [90]:
data[names == 'Bob', 2:]

array([[-1.68950219,  0.38049711],
       [-0.51737801, -0.25058465]])

In [91]:
data[names == 'Bob', 3]

array([ 0.38049711, -0.25058465])

If you know SQL, this is like the query:

```sql
SELECT col3, col4 FROM data WHERE name = 'Bob'
```

## Negation

Here are some examples of negated boolean operations being applied.

In [92]:
bix = names != 'Bob'
bix

array([False,  True,  True, False,  True,  True,  True])

In [93]:
data[bix]

array([[ 0.26840002,  1.04588115, -0.27682064,  1.34172096],
       [ 0.5600871 ,  0.40689673, -1.01778694, -1.26397703],
       [-0.41433972, -0.31894006,  0.13259035, -0.78374819],
       [ 0.25037425, -0.09460502, -0.08853394, -1.96423597],
       [ 1.20040478, -0.03586405, -0.85179925,  0.02612226]])

In [94]:
data[~bix] # Back to Bob

array([[-0.02296517,  0.13474624, -1.68950219,  0.38049711],
       [-0.30857368,  0.13819812, -0.51737801, -0.25058465]])

In [95]:
data[~(names == 'Bob')]

array([[ 0.26840002,  1.04588115, -0.27682064,  1.34172096],
       [ 0.5600871 ,  0.40689673, -1.01778694, -1.26397703],
       [-0.41433972, -0.31894006,  0.13259035, -0.78374819],
       [ 0.25037425, -0.09460502, -0.08853394, -1.96423597],
       [ 1.20040478, -0.03586405, -0.85179925,  0.02612226]])

Note that we don't use `not` but instead the tilde `~` sign to negate (flip) a value.

Nor do we use `and` and `or`; instead we use `&` and `|`.

Also, expressions join by these operators need to be in parentheses.

In [96]:
mask = (names == 'Bob') | (names == 'Will')
mask
data[mask]

array([[-0.02296517,  0.13474624, -1.68950219,  0.38049711],
       [ 0.5600871 ,  0.40689673, -1.01778694, -1.26397703],
       [-0.30857368,  0.13819812, -0.51737801, -0.25058465],
       [-0.41433972, -0.31894006,  0.13259035, -0.78374819]])

In [97]:
data[data < 0] = 0
data

array([[0.        , 0.13474624, 0.        , 0.38049711],
       [0.26840002, 1.04588115, 0.        , 1.34172096],
       [0.5600871 , 0.40689673, 0.        , 0.        ],
       [0.        , 0.13819812, 0.        , 0.        ],
       [0.        , 0.        , 0.13259035, 0.        ],
       [0.25037425, 0.        , 0.        , 0.        ],
       [1.20040478, 0.        , 0.        , 0.02612226]])

In [98]:
data[names != 'Joe'] = 7
data

array([[7.        , 7.        , 7.        , 7.        ],
       [0.26840002, 1.04588115, 0.        , 1.34172096],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [0.25037425, 0.        , 0.        , 0.        ],
       [1.20040478, 0.        , 0.        , 0.02612226]])

## Fancy Indexing

In so-call fancy indexing, we use array index numbers to access data.

This can be used to sub-select and re-order data from an array.

We pass a `list` of item numbers, instead of an integer or integer range with `:`, to the indexer.

In [99]:
arr = np.empty((8, 4))
for i in range(8):
    arr[i] = i
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

The following says _Select rows 4, 3, 0, and 6, in that order._

In [100]:
arr[[4, 3, 0, 6]]

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [0., 0., 0., 0.],
       [6., 6., 6., 6.]])

And we can go backwards.

In [101]:
arr[[-3, -5, -7]]

array([[5., 5., 5., 5.],
       [3., 3., 3., 3.],
       [1., 1., 1., 1.]])

We can use lists to perform some complex indexing.

In [102]:
arr = np.arange(32).reshape((8, 4))
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [103]:
arr[[1, 5, 7, 2], [0, 3, 1, 2]]  # Grab rows, then select columns from each row

array([ 4, 23, 29, 10])

In [104]:
arr[[1, 5, 7, 2]][:, [0, 3, 1, 2]] # Grab rows, then reorder columns 

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

## Transposing Arrays and Swapping Axes

Transposing is a special form of reshaping which similarly returns a view on the underlying data without copying anything. 

Arrays have the transpose method and also the special `T` attribute:

In [105]:
arr = np.arange(15).reshape((3, 5))
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [106]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

Transposing is often used when computing the dot product between two arrays.

Here's an example.

In [107]:
arr = np.random.randn(6, 3)
arr

array([[ 0.13663893,  1.00187709, -0.49963842],
       [-0.36045802,  0.11501271,  0.39756581],
       [ 0.14672184, -0.2152224 ,  2.09433159],
       [-1.6139847 ,  0.74614412, -2.0898423 ],
       [ 0.12286791,  0.57296788, -0.18656951],
       [ 1.16320932,  0.97720159,  2.05399248]])

In [108]:
np.dot(arr.T, arr)

array([[ 4.14322653,  0.0666845 ,  5.83498162],
       [ 0.0666845 ,  2.90325249, -0.5646554 ],
       [ 5.83498162, -0.5646554 , 13.41505604]])

For higher dimensional arrays, `transpose` will accept a tuple of axis numbers to permute the axes.

Warning -- this can get confusing to conceptualize and visualize!

In [109]:
arr = np.arange(16).reshape((2, 2, 4))
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [110]:
arr.transpose((1, 0, 2))

array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])

Simple transposing with `.T` is just a special case of swapping axes. ndarray has the method `swapaxes` which takes a pair of axis numbers:

In [111]:
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [112]:
arr.swapaxes(1, 2)

array([[[ 0,  4],
        [ 1,  5],
        [ 2,  6],
        [ 3,  7]],

       [[ 8, 12],
        [ 9, 13],
        [10, 14],
        [11, 15]]])

## Universal Functions

A universal function, or `ufunc`, is a function that performs elementwise operations on data in ndarrays. You can think of them as **fast vectorized wrappers for simple functions** that take one or more scalar values and produce one or more scalar results.

Many `ufuncs` are simple elementwise transformations, like `sqrt` or `exp`:

In [113]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [114]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [115]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [116]:
x = np.random.randn(8)
x

array([-1.21162715,  1.6337135 , -1.31514057, -0.5011741 , -0.32977931,
       -0.98463553, -1.69646137, -1.26292282])

In [117]:
y = np.random.randn(8)
y

array([-0.39375855, -0.29120602, -0.0876911 ,  1.52726809, -1.3897972 ,
        0.50625101, -0.19356104, -0.84859896])

In [118]:
np.maximum(x, y)

array([-0.39375855,  1.6337135 , -0.0876911 ,  1.52726809, -0.32977931,
        0.50625101, -0.19356104, -0.84859896])

In [119]:
arr = np.random.randn(7) * 5
arr

array([ -1.17483839,  -0.24073258,  -2.0693242 ,  -4.78731354,
         0.68248984,   9.1717787 , -11.70612985])

In [120]:
remainder, whole_part = np.modf(arr)
remainder

array([-0.17483839, -0.24073258, -0.0693242 , -0.78731354,  0.68248984,
        0.1717787 , -0.70612985])

In [121]:
whole_part

array([ -1.,  -0.,  -2.,  -4.,   0.,   9., -11.])

In [122]:
arr

array([ -1.17483839,  -0.24073258,  -2.0693242 ,  -4.78731354,
         0.68248984,   9.1717787 , -11.70612985])

In [123]:
np.sqrt(arr)

/var/folders/14/rnyfspnx2q131jp_752t9fc80000gn/T/ipykernel_58994/2296558006.py:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(arr)


array([       nan,        nan,        nan,        nan, 0.82612943,
       3.02849446,        nan])

`nan` is a special value in NumPy.
