# NB: NumPy Operations

Programming for Data Science

## Element-wise Arithmetic

NumPy arrays can be transformed with with arithmetic operations.

These are all **element-wise operations**.

Let's start with a 2D array.

In [32]:
arr = np.array([[1., 2., 3.], [4., 5., 6.]])
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [34]:
arr * arr

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [35]:
arr - arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [36]:
1 / arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [37]:
arr ** 0.5

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

Now let's compare two arrays.

In [38]:
arr2 = np.array([[0., 4., 1.], [7., 2., 12.]])
arr2

array([[ 0.,  4.,  1.],
       [ 7.,  2., 12.]])

In [39]:
arr2 > arr

array([[False,  True, False],
       [ True, False,  True]])

Boolean arrays will prove to be very useful ...

## Views and Copies

Notice that if we assign a scalar to a slice, all of the elements of the slice get that value. 

This is called **broadcasting**. We'll look at this more later.

Also, notice that changes to slices are changes to the arrays they are slices of. 

They are **views**, not copies. **This is crucial.**

See what happens when we change a view:

In [53]:
arr_slice = arr[5:8]
arr_slice

array([12, 12, 12])

In [54]:
arr_slice[1] = 12345
arr

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,
           9])

In [55]:
arr_slice[:] = 64

In [56]:
arr_slice

array([64, 64, 64])

In [57]:
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

NumPy defaults to views rather than copies because copies are **expensive** and NumPy is designed with large data use cases in mind.

If you want a copy of a slice of an ndarray instead of a view, use `.copy()`.

Here's an example:

In [58]:
arr_slice_copy = arr[5:8].copy()

In [59]:
arr_slice_copy

array([64, 64, 64])

In [60]:
arr_slice_copy[:] = 99

In [61]:
arr_slice_copy

array([99, 99, 99])

Note how the original array is unchanged:

In [62]:
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

## Broadcasting

What happens when you try to perform an element-wise operation on two arrays of different shape?

NumPy will convert a low-dimensional array into a high-dimensional array to allow the operation to take place.

This is called **broadcasting**.

Let's look at at our array `foo`:

In [20]:
foo

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

If we multiply it by 5, the scalar is converted into an array of the same shape as `foo` with the value 5 broadcast to populate the entire array.

In [21]:
foo * 5

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

If we want to multiply an array by a vector, the vector is broadcast to become a 2D array.

In [22]:
foo * np.array([5, 10, 6, 8])

array([[ 5., 10.,  6.,  8.],
       [ 5., 10.,  6.,  8.],
       [ 5., 10.,  6.,  8.],
       [ 5., 10.,  6.,  8.],
       [ 5., 10.,  6.,  8.],
       [ 5., 10.,  6.,  8.]])

Note that NumPy can't always make the adjustment:

In [23]:
foo * np.array([5, 10])

ValueError: operands could not be broadcast together with shapes (6,4) (2,) 