# M05 Notes

# Type Checking

The function `type()` does not return a string value, so you can't test for a type in this way:

In [45]:
x = "foo"

In [46]:
type(x) == 'str'

False

The return value of `type()` is not a string:

In [47]:
type(x)

str

We can see that this is not a string by doing this:

In [48]:
type(type(x))

type

So, you can compare the return value with one of Python's built-in data type objects:

In [49]:
type(x) == str

True

Pythons built-in data types include `str`, `float`, `int`, and `bool`.

Why use `isinstance()`?

For one thing, you can compare a value to multiple data types at once:

In [33]:
x1 = .1

isinstance(x1, int), isinstance(x1, float), isinstance(x1, (float, int))

(False, True, True)

# Points

- NumPy introduces a new data structure and new data types.
- Pandas is built on top of NumPy.
- NumPy is foundational to the Python data science toolbox -- SciPy, SciKit Learn, etc.

# Shape

In [2]:
import numpy as np

In [36]:
a = np.ones((4,4))

In [37]:
a

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

**One column matrix**

In [52]:
a[[0]]

array([[1., 1., 1., 1.]])

In [51]:
a[[0]].shape

(1, 4)

**Vector**

In [42]:
a[0]

array([1., 1., 1., 1.])

In [41]:
a[0].shape

(4,)